"use strict"

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

function Fibonacci() {
 	this.p0 = 1;
  	this.p1 = 1;
 	this.n = 1
}
Fibonacci.prototype.next = function() {
 	var result = this.n;
  	this.n = this.p0 + this.p1;
  	this.p0 = this.p1;
  	this.p1 = this.n;

	return result;
}

var fibs = [];
var f = new Fibonacci();
var n = f.next();
var sum = 0;
var limit = 4000000;

while (n < limit) {
	fibs.push(n);
	n = f.next();
}

var result = fibs.filter(function(n) {
	return n % 2 == 0;
}).reduce(function(acc, n) {
	return acc + n;
}, 0);

console.log(result);