package prob002;

import util.Fibonacci;

import java.util.stream.Stream;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem002 {
    public static void main(String... args) {
        final Stream<Long> fibs = Fibonacci.stream();
        final Long limit = 4000000l;

        final Long res = fibs.filter(l -> l < limit).filter(l -> l % 2 == 0).reduce(0l, (acc, curr) -> acc + curr);
        System.out.println(res);
   }
}